server:
  port: 7081
spring:
  application:
    name: fraud
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fraud
    username: root
    password: material4u@
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true